name: Crypto Alert Bot

on:
  schedule:
    - cron: '0 */4 * * *' # Cada 4 horas
  workflow_dispatch: # Ejecución manual

jobs:
  run-alert:
    runs-on: ubuntu-latest
    # Forzamos el uso de Node24 para todas las acciones del runner
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4 # Esta versión ahora correrá sobre Node24 por el env
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          pip install pandas yfinance requests

      - name: Ejecutar script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        run: python alert.py

      - name: Commit and push state
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add alert_state.json
          git commit -m "Update alert state [skip ci]" || exit 0
          git push
